# Generated by Django 3.2 on 2023-08-22 19:49

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[recipes.validators.Slug_Validator], verbose_name='Уникальный слаг'),
        ),
    ]
